kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle
spec:
  selector:
    matchLabels:
      app: lifecycle
  template:
    metadata:
      labels:
        app: lifecycle
    spec:
      containers:
      - name: lifecycle
        image: curlimages/curl:7.73.0
        command: ["/bin/sh","-c", "sleep infinity"]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "curl nginx -X GET --data \"app has been started\""]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "curl nginx -X POST --data \"app has been stopped\""]