apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: restricted
  name: deny-from-other-namespaces
spec:
  podSelector: 
    matchLabels: {}
  ingress:
  - from:
    - podSelector: {}