kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: index-html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index-html-volume
        secret:
          secretName: index-html
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx

---

echo -n $STRING | base64
echo -n $BASED_STRING | base64 --decode

---
apiVersion: v1
data:
  index.html: WW91ciBmaXJzdCBzZWNyZXQgaXMgbW91bnRlZA==
kind: Secret
metadata:
  name: index-html
