apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wp-pl-egress
spec:
  podSelector:
    matchLabels:
      run: busybox
  egress:
  - to:
    - ipBlock:
        cidr: 212.77.98.9/32
  policyTypes:
  - Egress