apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: secure-volume
        mountPath: /data
    securityContext:
      allowPrivilegeEscalation: false 
    command: ["/bin/bash", "-c", "sleep infinity"]
  securityContext:
    runAsNonRoot: true
  volumes:
  - name: secure-volume
    emptyDir: {}
    
