apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod-1
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
  containers:
  - name: security-context-container-1
    image: ubuntu
    command: ["/bin/sh","-c","sleep infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod-2
spec:
  securityContext:
    fsGroup: 2001
  containers:
  - name: security-context-container-2
    image: ubuntu
    command: ["/bin/sh","-c","sleep infinity"]
    volumeMounts:
    - name: sec-vol
      mountPath: /data
  volumes:
  - name: sec-vol
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod-3
spec:
  containers:
  - name: security-context-container-3
    image: ubuntu
    command: ["/bin/sh","-c","sleep infinity"]
    volumeMounts:
    - name: sec-vol
      mountPath: /data
    securityContext:
      readOnlyRootFilesystem: true
  volumes:
  - name: sec-vol
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-pod-4
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: security-context-container-1
    image: ubuntu
    command: ["/bin/sh","-c","sleep infinity"]