apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  namespace: default
spec:
  concurrencyPolicy: Replace
  suspend: no
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu
            args: ['/bin/sh', '-c', 'date; echo job successfull; sleep 180']
          restartPolicy: OnFailure