apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  restartPolicy: Always
  hostname: nginxos
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
    env:
    - name: POD_ENV1
      value: "This are yours"
    - name: POD_ENV2
      value: "first pod env vars!!"
    command: ["/bin/sh", "-c", "echo $POD_ENV1 $POD_ENV2 && hostname && sleep infinity"]
    ports:
    - containerPort: 80